Workwear/Models/ProductSize.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Workwear.ViewModels;

namespace Workwear.Models
{
    public class ProductSize
    {
        public int Id { get; set; }
        public string SizeName { get; set; }
        [Range(0, int.MaxValue)]
        public int Quantity { get; set; }
        public int ProductId { get; set; }
        [ForeignKey("ProductId")]
        [ValidateNever]
        public Product Product { get; set; }
    }
}

Workwear/Areas/Admin/Controllers/ProductSizeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data;
using Workwear.Data;
using Workwear.Models;
using Workwear.Repository;
using Workwear.Repository.IRepository;
using Workwear.Utility;
using Workwear.ViewModels;

namespace Workwear.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class ProductSizeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public ProductSizeController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            List<ProductSize> objProductSizeList = _unitOfWork.ProductSize.GetAll(includeProperties:"Product").ToList();
            return View(objProductSizeList);
        }
        public IActionResult Upsert(int? id)
        {
            ProductSizeVM sizeVM = new()
            {
                ProductList = _unitOfWork.Product.GetAll().Select(x => new SelectListItem
                {
                    Text = x.Title,
                    Value = x.Id.ToString(),
                }),
                ProductSize = new ProductSize()
            };
            if (id == null || id == 0)
            {
                return View(sizeVM);
            }
            else
            {
                sizeVM.ProductSize = _unitOfWork.ProductSize.Get(x => x.Id == id);
                return View(sizeVM);
            }
            
        }

        [HttpPost]
        public IActionResult Upsert(ProductSizeVM SizeVM)
        {
            if (ModelState.IsValid)
            {
                if (SizeVM.ProductSize.Id == 0) // Проверка на новую запись
                {
                    _unitOfWork.ProductSize.Add(SizeVM.ProductSize);
                }
                else
                {
                    _unitOfWork.ProductSize.Update(SizeVM.ProductSize);
                }

                _unitOfWork.Save();
                TempData["success"] = "Успешно";
                return RedirectToAction("Index");
            }
            else
            {
                SizeVM.ProductList = _unitOfWork.Product.GetAll().Select(x => new SelectListItem
                {
                    Text = x.Title,
                    Value = x.Id.ToString(),
                });
                return View(SizeVM);
            }
        }



        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            ProductSize? productsizeFromDb = _unitOfWork.ProductSize.Get(x => x.Id == id);
            if (productsizeFromDb == null)
            {
                return NotFound();
            }
            return View(productsizeFromDb);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePOST(int? id)
        {
            ProductSize? obj = _unitOfWork.ProductSize.Get(x => x.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            _unitOfWork.ProductSize.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = "Успешно";
            return RedirectToAction("Index");
        }
    }
}

Workwear/Areas/Admin/Views/ProductSize/Delete.cshtml
@model ProductSize


<div class="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-dark ml-0 py-4">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2>">Удалить размер</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post">
            <input asp-for="Id" hidden />
            <div class="border p-3 mt-4">
                <div class="form-floating py-2 col-12">
                    <input asp-for=SizeName class="form-control border-0 shadow" />
                    <label asp-for=SizeName class="ms-2"></label>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for=Quantity class="form-control border-0 shadow" />
                    <label asp-for=Quantity class="ms-2"></label>
                </div>

                <div class="row mt-3">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-danger form-control">Удалить</button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="ProductSize" asp-action="Index" class="btn btn-outline-secondary form-control">
                            Назад
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

Workwear/Areas/Admin/Views/ProductSize/Index.cshtml
@model IEnumerable<ProductSize>

<div class="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-black ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Размеры</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <div class="row pb-3">
            <div class="col-6">
            </div>
            <div class="col-6 text-end">
                <a asp-controller="ProductSize" asp-action="Upsert" class="btn btn-primary">
                    <i class="bi bi-plus-circle"></i> Добавить новый размер
                </a>
            </div>
        </div>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th> 
                    Размер
                </th>
                <th>
                    Количество
                </th>
                <th>
                    Товар
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td>@obj.SizeName</td>
                        <td>@obj.Quantity</td>
                        <td>@obj.Product.Title</td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="ProductSize" asp-action="Upsert" asp-route-Id="@obj.Id" class="btn btn-primary mx-2">
                                <i class="bi bi-pencil-square"></i> Изменить
                            </a>
                            <a asp-controller="ProductSize" asp-action="Delete" asp-route-Id="@obj.Id" class="btn btn-danger mx-2">
                                <i class="bi bi-trash-fill"></i> Удалить
                            </a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    </div>
    </div>

Workwear/Areas/Admin/Views/ProductSize/Upsert.cshtml
@model ProductSizeVM

<div class="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-dark ml-0 py-4">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2"> @(Model.ProductSize.Id!=0?"Изменить":"Добавить") размер</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post" class="row">
            <input asp-for="ProductSize.Id" hidden/>
            <div class="border p-3">
                <div class="form-floating py-2 col-12">
                    <select asp-for="ProductSize.ProductId" asp-items="@Model.ProductList" class="form-control border-0 shadow">
                        <option disabled selected>Выберите товар</option>
                    </select>
                    <label asp-for="ProductSize.ProductId" class="ms-2"></label>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="ProductSize.SizeName" class="form-control border-0 shadow" />
                    <label asp-for="ProductSize.SizeName" class="ms-2"></label>
                    <span asp-validation-for="ProductSize.SizeName" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="ProductSize.Quantity" class="form-control border-0 shadow" />
                    <label asp-for="ProductSize.Quantity" class="ms-2"></label>
                    <span asp-validation-for="ProductSize.Quantity" class="text-danger"></span>
                </div>

                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        @if (Model.ProductSize.Id != 0)
                        {
                            <button type="submit" class="btn btn-primary form-control">Изменить</button>
                        }
                        else
                        {
                            <button type="submit" class="btn btn-primary form-control">Создать</button>
                        }
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="ProductSize" asp-action="Index" class="btn btn-outline-secondary form-control">
                            Назад
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}